apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vproapp
  namespace: vproapp
  labels:
    app:  vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app:  vproapp
    spec:
      initContainers:
        - name: db-init-dependancy
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for vprodb; sleep 2; done"]
        - name: rabbitmq-init-dependancy
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup vpromq01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for vpromq01; sleep 2; done"]
      containers:
      - name:  vproapp
        image:  thdh/vproapp:v1.0
        ports:
        - containerPort:  8080
          name:  vproapp-port