apiVersion: v1
kind: PersistentVolume
metadata:
  name: vprodb-data-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-04a6fa581e45fb261  
    fsType: ext4  