apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vpromq01
  namespace: default
  labels:
    app:  vpromq01
spec:
  selector:
    matchLabels:
      app: vpromq01
  replicas: 1
  template:
    metadata:
      labels:
        app:  vpromq01
    spec:
      containers:
      - name:  vpromq01
        image:  rabbitmq:latest
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: rmq-pwd
        - name:  RABBITMQ_DEFAULT_USER
          value: "guest"
        ports:
        - containerPort:  15672
          name:  vpromq01-port